version: '3.1'

services:
  mybooking_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9003:9885
    depends_on:
      - "mybooking_db"
  mybooking_db:
      image: postgres
      restart: always
      ports:
            - 5422:5432
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: mybooking