spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5430/mybooking
    username: postgres
    password: postgres

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 9885

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE