spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mybooking
    username: postgres
    password: postgres

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 9885