INSERT INTO MYBOOKING_ROLE (ID, NAME) VALUES (101, 'TEST_CUSTOMER');

INSERT INTO MYBOOKING_USER (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (100, 'Michal', 'Cholewinski', 'cholewinski@onet.eu');
INSERT INTO MYBOOKING_USERS_ROLES (USER_ID, ROLE_ID) VALUES (100, 101);

INSERT INTO MYBOOKING_USER (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (101, 'Kacper', 'Karpinski', 'karpinski@onet.eu');
INSERT INTO MYBOOKING_USERS_ROLES (USER_ID, ROLE_ID) VALUES (101, 101);

INSERT INTO MYBOOKING_USER (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (102, 'Tomasz', 'Andrzejczak', 'andrzejczak@onet.eu');
INSERT INTO MYBOOKING_USERS_ROLES (USER_ID, ROLE_ID) VALUES (102, 101);

INSERT INTO MYBOOKING_USER (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (103, 'Marcin', 'Kowalski', 'kowalski@onet.eu');
INSERT INTO MYBOOKING_USERS_ROLES (USER_ID, ROLE_ID) VALUES (103, 101);