INSERT INTO MYBOOKING_ROLE (ID, NAME) VALUES (100, 'TEST_OWNER');
INSERT INTO MYBOOKING_ROLE (ID, NAME) VALUES (101, 'TEST_CUSTOMER');
INSERT INTO MYBOOKING_ROLE (ID, NAME) VALUES (102, 'TEST_ADMIN');
INSERT INTO MYBOOKING_ROLE (ID, NAME) VALUES (103, 'TEST_OTHER');