INSERT INTO MYBOOKING_ROLE (ID, NAME) VALUES (1, 'OWNER');
INSERT INTO MYBOOKING_ROLE (ID, NAME) VALUES (2, 'CUSTOMER');

INSERT INTO MYBOOKING_USER (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (1, 'Michal', 'Cholewinski', 'bulko@onet.eu');
INSERT INTO MYBOOKING_USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);